variables:
  PROJECT_PATH: arsnova.click
  MIRROR_REPO: git@github.com:thm-projects/arsnova.click.git
  NODE_ENV: production

jshint:
  stage: test
  tags:
    - nodejs
  dependencies: []
  script:
    - npm install jshint@^2.9.0
    - node_modules/jshint/bin/jshint --config .jshintrc $PROJECT_PATH/client/ $PROJECT_PATH/server/ $PROJECT_PATH/shared/

jscs:
  stage: test
  tags:
    - nodejs
  dependencies: []
  script:
    - npm install jscs
    - node_modules/jscs/bin/jscs --config .jscsrc $PROJECT_PATH/{lib,server,shared}/ $PROJECT_PATH/client/{layout,plugins} $PROJECT_PATH/client/routes.js

sonar:
  stage: test
  only:
    - master
    - staging
  tags:
    - gradle
  allow_failure: true
  dependencies: []
  script:
    - gradle sonarqube

build:
  stage: build
  only:
    - master
    - staging
    - /^v[0-9]+/
  tags:
    - meteor
  image: local-nodejs-meteor:1.6
  dependencies: []
  script:
    - test -d package-metadata && rm -rf /opt/meteor/package-metadata && mv package-metadata /opt/meteor/
    - cd "$PROJECT_PATH"
    - npm install
    - meteor build --allow-superuser --server-only --directory ../build
    - mv /opt/meteor/package-metadata "$CI_PROJECT_DIR/"
  cache:
    paths:
      - package-metadata
      - $PROJECT_PATH/.meteor/local
  artifacts:
    paths:
      - build/bundle/

deploy_production:
  stage: deploy
  only:
    - master
  tags:
    - ssh
  dependencies:
    - build
  script:
    - chmod -R a+rX,ug+w build
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh && echo "$PRODUCTION_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - ssh-add <(echo "$PRODUCTION_SSH_PRIVATE_KEY")
    - scp -r build/bundle/* "$PRODUCTION_SSH_URL"
  environment: production

sync_mirror:
  stage: deploy
  tags:
    - git
  when: always
  allow_failure: true
  dependencies: []
  script:
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh && echo "$SYNC_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - ssh-add <(echo "$SYNC_SSH_PRIVATE_KEY")
    - git clone --bare "$CI_REPOSITORY_URL" mirror.git
    - cd mirror.git
    - git push --mirror "$MIRROR_REPO"
